rework documentation on Singularity integration
shahzebsiddiqui/easybuild pull request #2
Opened 2018-04-23 18:43 UTC by boegel

more structured/general version for docs on new `--containerize` support: https://github.com/easybuilders/easybuild/pull/414

2018-04-23 18:44 UTC, boegel commented
@shahzebsiddiqui There are a couple of `FIXME`s here, mainly output of commands.

https://github.com/boegel/easybuild/blob/container_docs/docs/Containers.rst is probably easier to review.

2018-04-23 19:05 UTC, shahzebsiddiqui requested changes
needs to be fixed

2018-04-23 19:05 UTC, shahzebsiddiqui commented on docs/Containers.rst
> +    $ eb -C --container-build-image Python-3.6.4-foss-2018a.eb --container-base foss-2018a.simg
It should be the following

```
$ eb -C --container-build-image Python-3.6.4-foss-2018a.eb --container-base localimage:$PWD/foss-2018a.simg
```

2018-04-24 13:35 UTC, shahzebsiddiqui approved these changes

2018-04-24 13:55 UTC, merged